name: Connect to GCP and List Instances

on:
  push:
    branches: [ "dev" ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  setup-prepare-list:
    name: Setup, Prepare
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_ID }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Run Python Script
        run: python data/pubsub.py
